version: "3"

services:
  todo_spring_api:
    image: todo_spring_image
    ports:
      - "8080:8080"
    container_name: "todo_spring_api"
    networks:
      - todo_spring_net
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres
    ports:
      - "5432:5432"
    container_name: "postgres_todo_spring"
    restart: unless-stopped
    volumes:
      - db_todo_spring:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: todo_spring_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - todo_spring_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  todo_spring_net:
    driver: bridge
    name: "todo_spring_net"

volumes:
  db_todo_spring:
    name: "db_todo_spring"