version: "3"

services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    container_name: "postgres_todo_spring"
    restart: always
    volumes:
      - db_todo_spring:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB: todo_spring_api
      - POSTGRES_USER: postgres
      - POSTGRES_PASSWORD: postgres

volumes:
  db_todo_spring:
    name: "db_todo_spring"